### PR TITLE
.NET6 / Optimizely CMS 12 - Fix deployment issues

### PR DESCRIPTION
**Pull request by OMGPizzaGuy**
Building and debugging the feature/netcore branch worked for me, but when deployed it did not copy the module zip.
This PR should fix that issue. 

-Added PackageCopyToOutput and BuildAction flags to fix deployment problems

### CODE REVIEW

**Comment by OMGPizzaGuy** [comment]
Additional update to .NET 6 as current LTS release and allow EPiServer.Find.Cms 15

**Comment by OMGPizzaGuy** [comment]
@haugsten Any chance of moving forward with CMS-12 support? It seems stable and it might be better to note the remaining unsolved issues with HideFromViewMenu than waiting indefinitely.

**Comment by OMGPizzaGuy** [comment]
@haugsten - Great to see this, but I think there was an out of order merge. This went into the feature branch after the merge to master, so master is missing the important change.
Since it's a small fix, I see no problem with handling it with whatever is the easiest method

**Comment by haugsten** [comment]
@OMGPizzaGuy Yes I realized my mistake too. I updated the file and the master branch with your fix before I created package for version 2.0.0 Let me know if you have any problems installing the package.

**Pull request merged**
